baseurl:        /
port:    4000

paginate: 5
markdown: kramdown
gems: ['jekyll-paginate']


picture:        "/images/me-pebblebeach.png"
twitter:        "https://twitter.com/tildedave"
github:         "https://github.com/tildedave"
linkedin:       "http://www.linkedin.com/pub/dave-king/29/ba1/734"
email:          "tildedave_at_gmail_dot_com"
rss:            "/feed.xml"

name:           tildedave.com
description:    Dave King blogs about software design, thinking techniques, and team processes.
url:            http://www.tildedave.com
