auto:           true
baseurl:        /
server:         true
server_port:    4000

paginate:       5
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

picture:        "https://c417313.ssl.cf1.rackcdn.com/me-beergarden.png"
twitter:        "https://twitter.com/tildedave"
github:         "https://github.com/tildedave"
linkedin:       "http://www.linkedin.com/pub/dave-king/29/ba1/734"
email:          "tildedave_at_gmail_dot_com"
rss:            "http://www.davehking.com/feed.xml"

name:           davehking.com
description:    Dave King blogs about software patterns, functional programming, and testing.
url:            http://www.davehking.com
