baseurl:        /
port:    4000

paginate:       5
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
gems: ['jekyll-image_resizer']


picture:        "https://c417313.ssl.cf1.rackcdn.com/me-bootstrap-talk.png"
twitter:        "https://twitter.com/tildedave"
github:         "https://github.com/tildedave"
linkedin:       "http://www.linkedin.com/pub/dave-king/29/ba1/734"
email:          "tildedave_at_gmail_dot_com"
rss:            "/feed.xml"

name:           davehking.com
description:    Dave King blogs about software patterns, functional programming, and testing.
url:            http://www.davehking.com
background:     https://c417313.ssl.cf1.rackcdn.com/austria-lake.jpg
